package com.jotase.garage.POJO;
// Generated 07-jun-2014 23:43:42 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="garage"
)
public class Customer  implements java.io.Serializable {


     private Integer idCostumer;
     private String name;
     private String lastName;
     private String idNumber;
     private String address;
     private String postalCode;
     private String email;
     private String phone;
     private String phone2;
     private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);

    public Customer() {
    }

    public Customer(String name, String lastName, String idNumber, String address, String postalCode, String email, String phone, String phone2, Set<Vehicle> vehicles) {
       this.name = name;
       this.lastName = lastName;
       this.idNumber = idNumber;
       this.address = address;
       this.postalCode = postalCode;
       this.email = email;
       this.phone = phone;
       this.phone2 = phone2;
       this.vehicles = vehicles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCostumer", unique=true, nullable=false)
    public Integer getIdCostumer() {
        return this.idCostumer;
    }
    
    public void setIdCostumer(Integer idCostumer) {
        this.idCostumer = idCostumer;
    }
    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="lastName", length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="idNumber", length=50)
    public String getIdNumber() {
        return this.idNumber;
    }
    
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }
    
    @Column(name="address", length=250)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="postalCode", length=10)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="phone", length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="phone2", length=50)
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Vehicle> getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set<Vehicle> vehicles) {
        this.vehicles = vehicles;
    }




}


