package com.jotase.garage.POJO;
// Generated 07-jun-2014 23:43:42 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * InterventionHasProducts generated by hbm2java
 */
@Entity
@Table(name="intervention_has_products"
    ,catalog="garage"
    , uniqueConstraints = {@UniqueConstraint(columnNames="interventionId"), @UniqueConstraint(columnNames="productId")} 
)
public class InterventionHasProducts  implements java.io.Serializable {


     private InterventionHasProductsId id;
     private Product product;
     private Intervention intervention;
     private Double qty;

    public InterventionHasProducts() {
    }

	
    public InterventionHasProducts(InterventionHasProductsId id, Product product, Intervention intervention) {
        this.id = id;
        this.product = product;
        this.intervention = intervention;
    }
    public InterventionHasProducts(InterventionHasProductsId id, Product product, Intervention intervention, Double qty) {
       this.id = id;
       this.product = product;
       this.intervention = intervention;
       this.qty = qty;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="interventionId", column=@Column(name="interventionId", unique=true, nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="productId", unique=true, nullable=false) ) } )
    public InterventionHasProductsId getId() {
        return this.id;
    }
    
    public void setId(InterventionHasProductsId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productId", unique=true, nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="interventionId", unique=true, nullable=false, insertable=false, updatable=false)
    public Intervention getIntervention() {
        return this.intervention;
    }
    
    public void setIntervention(Intervention intervention) {
        this.intervention = intervention;
    }
    
    @Column(name="qty", precision=22, scale=0)
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }




}


