package com.jotase.garage.POJO;
// Generated 07-jun-2014 23:43:42 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehicletype generated by hbm2java
 */
@Entity
@Table(name="vehicletype"
    ,catalog="garage"
)
public class Vehicletype  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);

    public Vehicletype() {
    }

    public Vehicletype(String name, Set<Vehicle> vehicles) {
       this.name = name;
       this.vehicles = vehicles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="vehicletype")
    public Set<Vehicle> getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set<Vehicle> vehicles) {
        this.vehicles = vehicles;
    }




}


